### PR TITLE
LazyLoadList

### PR DESCRIPTION
**Pull request by tplusrex**
Created a slick setting property that allows you to specify which slides to preload.

### CODE REVIEW

**Comment by gkilian** [comment]
What would be the use case for this feature? I figure you want specificity here but why wouldn't the offset suffice?

**Comment by gkilian** [comment]
I'm hesitant to release new features that are specific to a brands needs and may not be actual issues or something that will be upstreamed. That said I have very little context here and there may be a reason/issue.

Can we please open up issues in both the OSS repo and in this repo detailing the case?

**Comment by tplusrex** [comment]
We want the ability to load all Ad slides when gallery loads instead of waiting for the Ad slide to become active and then making an Ad call. The Ad slide appears after every 6th slide.

```
[slide, slide, slide, slide, slide, slide, ad, slide]
```
We want to load the 7th slide right away instead of having users wait. They'll most likely skip that slide if nothing appears. Makes for a poor Ad experience.

**Comment by tplusrex** [comment]
i'll create an issue in both repos

**Comment by gkilian** [comment]
Closing this -  This isn't a feature we'll want to propose back upstream. The use case seems to be more Conde specific.

**Pull request closed without merging**
