### PR TITLE
Shift to `create-react-class` for React 16 compatibility.

### PR DESCRIPTION
**Pull request by giles-v**
In using this repo for React 16, we need to change `React.createClass` to `createReactClass`. 

It should be possible to move this to `React.Component`, but right now the code uses mixins, so making that change would be a significant amount of work.

### CODE REVIEW

**Comment by gkilian** [comment]
@giles-v - This seems to have been already done in the main OOP repo. I'd prefer to bring this repo up to date with that and apply the commits on top, which are waiting to be upstreamed.

**Comment by gkilian** [comment]
https://github.com/akiran/react-slick/commit/d6c3ac96fb538da6f3564fc9013cd22903c4541c

**Comment by giles-v** [comment]
@gkilian I read on this repo's README that stuff was proposed to the upstream module, but I can't see a PR cited anywhere. Can you post a link?

**Comment by gkilian** [comment]
@giles-v - proposed as in a issue was created and a proposal for the features to be added. PRs haven't be created for those yet.

**Comment by gkilian** [comment]
@giles-v - Closing this in favor of https://github.com/CondeNast/react-slick/pull/14

**Comment by gkilian** [comment]
@giles-v - `condenast/cn-react-slick@0.16.0` has been released. https://github.com/CondeNast/react-slick/releases/tag/0.16.0

There is a noted **breaking change** which might cause breakage in Vogue's repo.

**Pull request closed without merging**
